#
# multi-stage build
# docker build --target testbuilder -t stillwater/universal:builder will just build a builder container
# docker build --target release -t stillwater/universal:release will just build a release container

# BUILDER stage
FROM gcc:10.3 as testbuilder
LABEL Theodore Omtzigt
ARG target=BUILD_ALL
# create a build environment
RUN apt-get update && apt-get install -y --no-install-recommends -V \
    apt-utils \
    build-essential \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

# install a specific cmake version
RUN set -ex \
  && for key in C6C265324BBEBDC350B513D02D2CEF1034921684; do \
    gpg --keyserver hkp://keyserver.ubuntu.com --recv-keys "$key" ; \
  done

ENV CMAKE_DIR v3.23
ENV CMAKE_VERSION 3.23.1

RUN set -ex \
  && curl -fsSLO --compressed https://cmake.org/files/${CMAKE_DIR}/cmake-${CMAKE_VERSION}-linux-x86_64.tar.gz \
  && curl -fsSLO https://cmake.org/files/${CMAKE_DIR}/cmake-${CMAKE_VERSION}-SHA-256.txt.asc \
  && curl -fsSLO https://cmake.org/files/${CMAKE_DIR}/cmake-${CMAKE_VERSION}-SHA-256.txt \
  && gpg --verify cmake-${CMAKE_VERSION}-SHA-256.txt.asc cmake-${CMAKE_VERSION}-SHA-256.txt \
  && grep "cmake-${CMAKE_VERSION}-linux-x86_64.tar.gz\$" cmake-${CMAKE_VERSION}-SHA-256.txt | sha256sum -c - \
  && tar xzf cmake-${CMAKE_VERSION}-linux-x86_64.tar.gz -C /usr/local --strip-components=1 --no-same-owner \
  && rm -rf cmake-${CMAKE_VERSION}*

# create and use user stillwater
RUN useradd -ms /bin/bash stillwater
USER stillwater

# make certain you have a good .dockerignore file installed so that this layer isn't ginormous
COPY --chown=stillwater:stillwater . /home/stillwater/universal
# print contextual information of the container at this state for visual inspection
RUN ls -la /home/stillwater/universal && cmake -version 

# set up the cmake/make environment to issue the build commands
RUN mkdir -p /home/stillwater/universal/build 
WORKDIR /home/stillwater/universal/build
# test RUN statement to speed-up CI testing
#RUN cmake -DBUILD_CMD_LINE_TOOLS=ON -DBUILD_EDUCATION=OFF -DBUILD_APPLICATIONS=OFF -DBUILD_PLAYGROUND=OFF .. && make
# full RUN statement to execute full regression test suite
RUN cmake -D$target=ON -DBUILD_DEMONSTRATION=OFF .. && make

# add a command that when you run the container without a command, it produces something meaningful
CMD ["echo", "Universal Numbers Library gcc build container"]


# RELEASE stage
#FROM alpine:latest as release    # hitting a segfault during startup of some playground programs
#FROM debian:buster-slim as release
FROM ubuntu:20.04 as release
LABEL Theodore Omtzigt

#RUN apk add --no-cache libc6-compat libstdc++ cmake make bash gawk sed grep bc coreutils
RUN apt-get update && apt-get install -y --no-install-recommends \
    make \
    && apt-get clean
# create and use user stillwater
RUN useradd -ms /bin/bash stillwater
USER stillwater

# copy cmake enviroment needed for testing
COPY --from=testbuilder /usr/local/bin/cmake /usr/local/bin/
COPY --from=testbuilder /usr/local/bin/ctest /usr/local/bin/
# copy information material
COPY --from=testbuilder /home/stillwater/universal/*.md /home/stillwater/universal/
# copy the docs
COPY --from=testbuilder /home/stillwater/universal/docs /home/stillwater/universal/docs
# no need to copy CMakeLists.txt as you don't have a compiler in this container 
# and thus 'make -j 8' won't work anyway, only 'make test' which doesn't need CmakeLists.txt
#COPY --from=testbuilder /home/stillwater/universal/CMakeLists.txt /home/stillwater/universal/

# after building, the test executables are organized in the build directory under stillwater
# ctest gets its configuration for CTestTestfile.cmake files. There is one at the root of the build tree
# and one for each directory that contains test executables.
# This way we can execute _make test_ in the test stage of the CI/CD pipeline as well as part of an interactive invocation
COPY --chown=stillwater:stillwater --from=testbuilder /home/stillwater/universal/build /home/stillwater/universal/build

# until we can figure out how to direct CodeShip to use this dir in the steps.yml file
WORKDIR /home/stillwater/universal/build 

RUN find .
RUN make test

CMD ["echo", "Universal Numbers Library gcc test container"]
