set(UNIVERSAL_COMMON_CONFIG "${UNIVERSAL_DIR}/tools/cmake/UNIVERSALCommon.cmake")
if( EXISTS ${UNIVERSAL_COMMON_CONFIG})
	include(${UNIVERSAL_COMMON_CONFIG})
else()
	message(ERROR "Could not find the common universal arithmetic library configuration.")
endif()
