message(STATUS "CMake version: ${CMAKE_VERSION}")

find_program(NINJA_EXE NAMES ninja)
if(NINJA_EXE)
  message(STATUS "Ninja: ${NINJA_EXE}")
else()
  message(STATUS "Ninja: not found")
endif()

find_program(CTEST_EXE NAMES ctest)
if(CTEST_EXE)
  message(STATUS "ctest: ${CTEST_EXE}")
else()
  message(STATUS "ctest: not found")
endif()

find_program(LLVM_PROFDATA_EXE NAMES llvm-profdata)
if(LLVM_PROFDATA_EXE)
  message(STATUS "llvm-profdata: ${LLVM_PROFDATA_EXE}")
else()
  message(STATUS "llvm-profdata: not found")
endif()

find_program(LLVM_COV_EXE NAMES llvm-cov)
if(LLVM_COV_EXE)
  message(STATUS "llvm-cov: ${LLVM_COV_EXE}")
else()
  message(STATUS "llvm-cov: not found")
endif()

find_program(GCOVR_EXE NAMES gcovr)
if(GCOVR_EXE)
  message(STATUS "gcovr: ${GCOVR_EXE}")
else()
  message(STATUS "gcovr: not found")
endif()
