if(NOT DEFINED QUERY)
  message(FATAL_ERROR "QUERY is required (JOBS, ARCH, or NINJA).")
endif()

function(_emit_result value)
  execute_process(COMMAND "${CMAKE_COMMAND}" -E echo "${value}")
endfunction()

if(QUERY STREQUAL "JOBS")
  cmake_host_system_information(RESULT _cores QUERY NUMBER_OF_LOGICAL_CORES)
  if(NOT _cores OR _cores LESS 1)
    set(_cores 1)
  endif()
  math(EXPR _jobs "${_cores}+1")
  _emit_result("${_jobs}")
elseif(QUERY STREQUAL "ARCH")
  if(DEFINED CMAKE_HOST_SYSTEM_PROCESSOR)
    _emit_result("${CMAKE_HOST_SYSTEM_PROCESSOR}")
  else()
    _emit_result("unknown")
  endif()
elseif(QUERY STREQUAL "HOST_OS")
  if(DEFINED CMAKE_HOST_SYSTEM_NAME)
    _emit_result("${CMAKE_HOST_SYSTEM_NAME}")
  else()
    _emit_result("unknown")
  endif()
elseif(QUERY STREQUAL "PROG")
  if(NOT DEFINED PROG_NAME)
    message(FATAL_ERROR "PROG_NAME is required when QUERY=PROG.")
  endif()
  find_program(PROG_EXE NAMES "${PROG_NAME}")
  if(PROG_EXE)
    if(PROG_NAME STREQUAL "gcc")
      execute_process(
        COMMAND "${PROG_EXE}" --version
        OUTPUT_VARIABLE _gcc_version
        ERROR_VARIABLE _gcc_version
        OUTPUT_STRIP_TRAILING_WHITESPACE
        ERROR_STRIP_TRAILING_WHITESPACE
      )
      string(TOLOWER "${_gcc_version}" _gcc_version_lc)
      string(FIND "${_gcc_version_lc}" "clang" _gcc_is_clang)
      if(NOT _gcc_is_clang EQUAL -1)
        # Prefer a real GCC if gcc is a clang shim (common on macOS).
        # Scan PATH for gcc* binaries and verify by running --version.
        set(_real_gcc "")
        set(_best_gcc_version -1)
        string(REPLACE ":" ";" _path_list "$ENV{PATH}")
        list(REMOVE_DUPLICATES _path_list)
        foreach(_dir IN LISTS _path_list)
          if(NOT _dir)
            continue()
          endif()
          if(NOT IS_DIRECTORY "${_dir}")
            continue()
          endif()
          file(GLOB _gcc_globs LIST_DIRECTORIES false "${_dir}/gcc*")
          foreach(_gcc_candidate IN LISTS _gcc_globs)
            if(NOT EXISTS "${_gcc_candidate}")
              continue()
            endif()
            if(NOT IS_EXECUTABLE "${_gcc_candidate}")
              continue()
            endif()
            execute_process(
              COMMAND "${_gcc_candidate}" --version
              OUTPUT_VARIABLE _gcc_cand_version
              ERROR_VARIABLE _gcc_cand_version
              OUTPUT_STRIP_TRAILING_WHITESPACE
              ERROR_STRIP_TRAILING_WHITESPACE
            )
            string(TOLOWER "${_gcc_cand_version}" _gcc_cand_version_lc)
            string(FIND "${_gcc_cand_version_lc}" "clang" _cand_is_clang)
            string(FIND "${_gcc_cand_version_lc}" "gcc" _cand_is_gcc)
            string(FIND "${_gcc_cand_version_lc}" "gnu" _cand_is_gnu)
            if(_cand_is_clang EQUAL -1 AND (NOT _cand_is_gcc EQUAL -1 OR NOT _cand_is_gnu EQUAL -1))
              # Prefer the highest gcc-N if present; otherwise take the first valid candidate.
              set(_cand_version_num -1)
              string(REGEX MATCH "gcc[-]?([0-9]+)" _gcc_name_match "${_gcc_candidate}")
              if(_gcc_name_match)
                set(_cand_version_num "${CMAKE_MATCH_1}")
              endif()
              if(_cand_version_num GREATER _best_gcc_version)
                set(_best_gcc_version "${_cand_version_num}")
                set(_real_gcc "${_gcc_candidate}")
              elseif(_real_gcc STREQUAL "" AND _cand_version_num EQUAL -1)
                set(_real_gcc "${_gcc_candidate}")
              endif()
            endif()
          endforeach()
        endforeach()
        if(_real_gcc)
          set(PROG_EXE "${_real_gcc}")
        endif()
      endif()
    endif()
    _emit_result("${PROG_EXE}")
  endif()
elseif(QUERY STREQUAL "NINJA")
  find_program(NINJA_EXE NAMES ninja)
  if(NINJA_EXE)
    _emit_result("${NINJA_EXE}")
  endif()
else()
  message(FATAL_ERROR "Unknown QUERY: ${QUERY}")
endif()
