if(NOT DEFINED QUERY)
  message(FATAL_ERROR "QUERY is required (JOBS, ARCH, or NINJA).")
endif()

function(_emit_result value)
  execute_process(COMMAND "${CMAKE_COMMAND}" -E echo "${value}")
endfunction()

if(QUERY STREQUAL "JOBS")
  cmake_host_system_information(RESULT _cores QUERY NUMBER_OF_LOGICAL_CORES)
  if(NOT _cores OR _cores LESS 1)
    set(_cores 1)
  endif()
  math(EXPR _jobs "${_cores}+1")
  _emit_result("${_jobs}")
elseif(QUERY STREQUAL "ARCH")
  if(DEFINED CMAKE_HOST_SYSTEM_PROCESSOR)
    _emit_result("${CMAKE_HOST_SYSTEM_PROCESSOR}")
  else()
    _emit_result("unknown")
  endif()
elseif(QUERY STREQUAL "NINJA")
  find_program(NINJA_EXE NAMES ninja)
  if(NINJA_EXE)
    _emit_result("Ninja")
  endif()
else()
  message(FATAL_ERROR "Unknown QUERY: ${QUERY}")
endif()
