#!/usr/bin/env python3
# efloat_constants_gen.py: generate high-precision decimal literals for the
# efloat mathematical constants (pi, e, phi) used by efloat_constants.hpp.
#
# Copyright (C) 2017 Stillwater Supercomputing, Inc.
# SPDX-License-Identifier: MIT
#
# Uses mpmath as the arbitrary-precision oracle. Emits ~1000 significant
# decimal digits per constant -- enough to fill a ~3300-bit efloat (about 104
# uint32 limbs), which exceeds the ~315-digit ceiling of the multi-component
# ereal/elreal constants (issue #1139).
#
# Usage:
#   python3 tools/generators/efloat_constants_gen.py [ndigits]
# Prints C++-ready `const char* ... = "...";` lines to stdout. The digit
# strings are pasted into efloat_constants.hpp. Regenerate to change ndigits.

import sys

try:
    import mpmath
except ImportError:
    sys.stderr.write("error: mpmath is required (pip install mpmath)\n")
    sys.exit(1)


def literal(x, ndigits):
    # mpmath.nstr with strip_zeros=False keeps the full fixed digit count.
    return mpmath.nstr(x, ndigits, strip_zeros=False)


def main():
    ndigits = int(sys.argv[1]) if len(sys.argv) > 1 else 1010
    mpmath.mp.dps = ndigits + 10  # guard digits

    consts = [
        ("EFLOAT_PI_DIGITS",  mpmath.pi),
        ("EFLOAT_E_DIGITS",   mpmath.e),
        ("EFLOAT_PHI_DIGITS", (1 + mpmath.sqrt(5)) / 2),
    ]
    print("// Generated by tools/generators/efloat_constants_gen.py"
          " -- do not edit by hand.")
    print("// %d significant decimal digits (mpmath oracle)." % ndigits)
    for name, value in consts:
        s = literal(value, ndigits)
        print('inline constexpr const char* %s =' % name)
        print('    "%s";' % s)


if __name__ == "__main__":
    main()
