// constants.cpp: Phase 7.1 (#931) tests for the lazy ZBCL constant factories.
//
// Series constants (e, ln2, ln10, log2(10), pi) are generated by Taylor/artanh/
// Machin series; on a double host they reach hundreds of bits. They are tested
// on {double, float} -- NOT bfloat16. The reason is bfloat16's narrow 7-bit
// significand (k=7), not its exponent range (which is the same 8-bit range as
// float): with k=7 a division-derived series operand such as 1/5 spans ~15
// blocks reaching down near the exponent floor (~2^-115), and squaring it inside
// mul() lands near 2^-230 -- far below the representable range -- which
// underflows. (float's 24-bit significand needs only ~3 blocks for 1/5, reaching
// ~2^-55, so its square stays in range.) Even at a small depth, where bfloat16
// series do run, its ~7-bit arithmetic caps accuracy at ~2-3 digits and does not
// improve with depth, so high-precision series constants are not meaningful on
// bfloat16. The radical constants (sqrt2/3/5, phi) and euler_gamma stay shallow
// and are tested on {double, float, bfloat16}.
//
// Validation: value vs the known host double, algebraic identities (sqrt(n)^2=n,
// phi^2=phi+1, 2^log2(10) round-trips via mul), 0-overlap on every result, and a
// "beyond-double" precision check for pi/e on the double host (full 100-digit
// reference-string verification is a follow-up; it needs a decimal->dyadic parse).
//
// Copyright (C) 2017 Stillwater Supercomputing, Inc.
// SPDX-License-Identifier: MIT
//
// This file is part of the universal numbers project, which is released under an MIT Open Source license.
#include <universal/utility/directives.hpp>
#include <cmath>
#include <iostream>
#include <numbers>
#include <string>
#include <vector>

#include <universal/number/elreal/elreal.hpp>
#include <universal/number/elreal/math/constants.hpp>
#include <universal/number/bfloat16/bfloat16.hpp>
#include <universal/verification/dyadic_exact.hpp>
#include <universal/verification/test_suite.hpp>

#include <universal/verification/elreal_oracle.hpp>

namespace {

namespace est = sw::universal::elreal_oracle;

template <typename FpType>
int check_value(const sw::universal::ZBCL<FpType>& z, double ref, double tol, const std::string& tag) {
    using namespace sw::universal;
    int n = 0;
    if (std::abs(est::approx(z) - ref) > tol) {
        std::cout << tag << " = " << est::approx(z) << " != " << ref << " (tol " << tol << ")\n"; ++n;
    }
    n += est::check_zero_overlap<FpType>(z, 24, tag);
    return n;
}

// Test generation depth. The constant generators default to deep precision (e=32,
// pi=16 blocks) for high-precision *use*, but these tests only compare against the
// host-double std::numbers reference (a ~1e-12 tolerance). Six blocks is ~300+ bits
// on a double host -- far past the reference -- while cutting generation cost by
// ~(6/16)^4 (and much more for e) vs the defaults, which is the dominant saving on
// this, the most expensive elreal math test, under the -O0/instrumented CI tiers.
static constexpr std::size_t kConstDepth = 6;

// Series constants -- tested on double / float only.
template <typename FpType>
int verify_series(double tol, const std::string& host, std::size_t depth) {
    using namespace sw::universal;
    int n = 0;
    n += check_value(e_zbcl<FpType>(depth),        std::numbers::e_v<double>,    tol, host + " e");
    n += check_value(ln2_zbcl<FpType>(depth),      std::numbers::ln2_v<double>,  tol, host + " ln2");
    n += check_value(ln10_zbcl<FpType>(depth),     std::numbers::ln10_v<double>, tol, host + " ln10");
    n += check_value(log2_10_zbcl<FpType>(depth),  std::log2(10.0),              tol, host + " log2(10)");
    n += check_value(pi_zbcl<FpType>(depth),       std::numbers::pi_v<double>,   tol, host + " pi");
    return n;
}

// Radical constants + euler_gamma -- tested on all hosts (stay in range).
template <typename FpType>
int verify_radicals(double tol, const std::string& host, std::size_t depth) {
    using namespace sw::universal;
    int n = 0;
    struct { ZBCL<FpType> z; double ref; const char* name; } rad[] = {
        { sqrt2_zbcl<FpType>(depth), std::numbers::sqrt2_v<double>, "sqrt2" },
        { sqrt3_zbcl<FpType>(depth), std::numbers::sqrt3_v<double>, "sqrt3" },
        { sqrt5_zbcl<FpType>(depth), std::sqrt(5.0),                "sqrt5" },
        { phi_zbcl<FpType>(depth),   std::numbers::phi_v<double>,   "phi"   },
    };
    for (auto& r : rad) n += check_value(r.z, r.ref, tol, host + " " + r.name);

    // Algebraic identities (tolerance-based; sqrt/phi are approximate streams).
    for (double v : { 2.0, 3.0, 5.0 }) {
        ZBCL<FpType> s = sqrt(from_native<FpType>(v), depth);
        if (std::abs(est::approx(mul(s, s)) - v) > tol) {
            std::cout << host << " sqrt(" << v << ")^2 != " << v << '\n'; ++n;
        }
    }
    {   // phi^2 == phi + 1
        ZBCL<FpType> phi = phi_zbcl<FpType>(depth);
        double lhs = est::approx(mul(phi, phi));
        double rhs = est::approx(add(phi, from_native<FpType>(1.0)));
        if (std::abs(lhs - rhs) > tol) { std::cout << host << " phi^2 != phi+1\n"; ++n; }
    }
    n += check_value(euler_gamma_zbcl<FpType>(depth), std::numbers::egamma_v<double>, tol, host + " egamma");
    return n;
}

// Beyond-double precision check for the double host: pi and e must agree with a
// multi-limb high-precision reference to well past double precision.
int verify_highprec_double() {
    using namespace sw::universal;
    int n = 0;
    // pi reference as a 3-limb non-overlapping double expansion (~159 bits).
    std::vector<block<double>> pilimbs = {
        block<double>{ 3.141592653589793,        0 },
        block<double>{ 1.2246467991473532e-16,   0 },
        block<double>{ -2.9947698097183397e-33,  0 },
    };
    ZBCL<double> ref = zbcl_from_blocks<double>(priestRenorm(pilimbs));
    // depth 8 (~424 bits) is the suite's one deliberately-deep generation, well
    // past the 3-limb (~159-bit) reference it is compared against.
    ZBCL<double> diff = add(pi_zbcl<double>(8), negate(ref));
    // Agreement to > 100 bits (~30 digits) demonstrates precision well beyond the
    // host double (the 3-limb reference itself caps the check at ~159 bits). The
    // leading limb cancels exactly, so the residual magnitude is the real signal
    // (do not read diff.head().exponent() -- that may be a zero block).
    const double residual = std::abs(to_double_approx(diff, 16));
    if (residual > 1e-30) {
        std::cout << "pi high-precision: residual " << residual << " too large (want < 1e-30)\n"; ++n;
    }
    return n;
}

} // anonymous

int main()
try {
    using namespace sw::universal;
    std::string test_suite = "elreal Phase 7.1 (#931) constants";
    int nrOfFailedTestCases = 0;
    bool reportTestCases = false;
    ReportTestSuiteHeader(test_suite, reportTestCases);

    nrOfFailedTestCases += verify_series<double>(1e-12, "const<double>", kConstDepth);
    nrOfFailedTestCases += verify_series<float>(1e-6, "const<float>", kConstDepth);

    nrOfFailedTestCases += verify_radicals<double>(1e-12, "const<double>", kConstDepth);
    nrOfFailedTestCases += verify_radicals<float>(1e-6, "const<float>", kConstDepth);
    nrOfFailedTestCases += verify_radicals<bfloat16>(1e-2, "const<bfloat16>", kConstDepth);

    nrOfFailedTestCases += verify_highprec_double();

    ReportTestSuiteResults(test_suite, nrOfFailedTestCases);
    return (nrOfFailedTestCases > 0 ? EXIT_FAILURE : EXIT_SUCCESS);
}
catch (const std::exception& err) {
    std::cerr << "Caught unexpected exception: " << err.what() << std::endl;
    return EXIT_FAILURE;
}
